# language: node_js
# node_js:
#   - 8
# cache: npm
# branches:
#   except:
#     - /^v[0-9]/
#     - /^feature*/
# script:
#   # - npm run lint
#   # - npm run test
#   - npm run build api
#   - npm run build:ssr
#   - npm run build cli
# addons:
#   ssh_known_hosts: "slackmap.com"
# before_deploy:
#   - openssl aes-256-cbc -K $encrypted_430392f7e341_key -iv $encrypted_430392f7e341_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
#   - eval "$(ssh-agent -s)"
#   - chmod 600 /tmp/deploy_rsa
#   - ssh-add /tmp/deploy_rsa
#   - chmod +x ./tools/scripts/deploy-test.sh
#   - git config credential.helper "store --file=.git/credentials"; echo "https://${GH_TOKEN}:@github.com" > .git/credentials 2>/dev/null
#   - git config --global user.email "travisci@slackmap.com"
#   - git config --global user.name "TravisCI"
# deploy:
#   - provider: script
#     skip_cleanup: true
#     script: bash ./tools/scripts/deploy-test.sh
#     on:
#       branch: develop
#   - provider: script
#     skip_cleanup: true
#     script: bash ./tools/scripts/deploy-prod.sh
#     on:
#       branch: master
# notifications:
#   email: false

language: node_js # Node.js based project
node_js:
  - 12 # Level of Node.js to use
cache:
  directories:
    - node_modules # Cache the node_modules folder for quicker build times
script:
  - npm run build # Runs next build
  - npm run export # Runs next export and generates the out directory
  - touch out/.nojekyll # Creates a file telling Github not to build the project using Jekyll
deploy:
  provider: pages # Informs Travis this is a deployment to GitHub Pages
  skip_cleanup: true # Prevents Travis from resetting the working directory made during the build
  github_token: $github_token # GitHub access token to use when pushing to the gh-pages branch
  local_dir: out # Directory to push to the gh-pages branch
  on:
    branch: dev_setup # Only deploy when the build is on master branch

